name: Manual deployment for Terraform Infrastructure

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        description: asdfas
        type: string
    # secrets:
      CLIENT_ID:
        required: true
        description: asdfas
        type: string
      CLIENT_SECRET:
        required: true
        description: asdfas
        type: string
      SUBSCRIPTION_ID:
        required: true
        description: asdfas
        type: string
      TENANT_ID:
        required: true
        description: asdfas
        type: string
      ENVIRONMENT:
        required: true
        description: asdfas
        type: string

jobs:
  deploy_tf:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      ARM_CLIENT_ID: ${{ inputs.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ inputs.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ inputs.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ inputs.TENANT_ID }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Terraform init
      id: init
      shell: bash
      run: |
        terraform init
      working-directory: ${{ env.ENVIRONMENT }}

    - name: Terraform plan
      id: plan
      shell: bash
      run: |
        terraform plan -out tf-$ENVIRONMENT-${GITHUB_SHA::7}.plan -input=false -lock=false
        tree
      working-directory: ${{ env.ENVIRONMENT }}

    - name: Terraform Apply
      shell: bash
      run: |
        terraform apply -input=false tf-$ENVIRONMENT-${GITHUB_SHA::7}.plan
      working-directory: ${{ env.ENVIRONMENT }}