name: Manual deployment for Terraform Infrastructure

on:
  release:
    types: [published]

jobs:
  deploy-tf:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    environment: development
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ENVIRONMENT: development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment (Push)  
      shell: bash  
      run: |  
        echo "LAST_COMMIT_SHA=${GITHUB_SHA::7}" >> ${GITHUB_ENV}
    - name: Download TF plan artifact
      uses: actions/download-artifact@v3
      with:
        name: plan-${{ env.LAST_COMMIT_SHA }}
        path: development/
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name: Terraform init
      id: init
      shell: bash
      run: |
        terraform init
      working-directory: $ENVIRONMENT
    - name: Terraform Apply
      shell: bash
      run: |
        terraform apply -input=false tf-$ENVIRONMENT-${GITHUB_SHA::7}.plan
      working-directory: $ENVIRONMENT