name: Manual deployment for Terraform Infrastructure

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true
      ENVIRONMENT:
        required: true

jobs:
  deploy_tf:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # with:
      #   ref: ${{ secrets.TENANT_ID }}
    - uses: actions/cache@v3
      with:
        path: development/tf.plan
        key: plan-file
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    # - name: Using azure cli
    #   uses: azure/login@v1
    #   env:
    #     AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #     AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #     AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    #     AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    # - name: Check Azure CLI version
    #   run: az --version
    # - name: Debug Azure CLI credentials
    #   run: |
    #     echo "AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}"
    #     echo "AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}"
    #     echo "AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}"
    # - name: Log in
    #   run: az login --service-principal --tenant ${{ secrets.TENANT_ID }} --username ${{ secrets.CLIENT_ID }} --password ${{ secrets.CLIENT_SECRET }}
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        tree
        terraform apply -input=false tf.plan
      working-directory: ${{ inputs.working-directory }}
      shell: bash