name: Manual deployment for Terraform Infrastructure

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ENVIRONMENT:
        required: true

jobs:
  deploy_tf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: development/tf.plan
        key: plan-file
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name: Log in
      uses: azure/login@v1
      run: az login --service-principal --tenant ${{ secrets.ARM_TENANT_ID }} --username ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }}
    - name: Terraform Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        ENVIRONMENT: development
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        tree
        terraform apply -input=false tf.plan
      working-directory: ${{ inputs.working-directory }}
      shell: bash