name: Deploy Terraform infrastructure

on:
  push:
    branches:
      - main
  release:
    types: [published]
    

jobs:
  setup-tf-modules:
    runs-on: ubuntu-latest
    name: Terraform init
    environment: development
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ENVIRONMENT: development
      SHORT_SHA: ${GITHUB_SHA::7}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  

  deploy-infra:
    name: Terraform Plan
    uses: lRaggnar/poc-gh-actions-terraform/.github/workflows/deploy-terraform.yml@main
    needs: setup-tf-modules
    with:
      working-directory: development
      ENVIRONMENT: development
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}