name: Deploy Terraform infrastructure

on:
  push:
    branches:
      - master
      - develop
      - /^release\/.*$/

jobs:
  setup-tf-modules:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: development
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ENVIRONMENT: development
      SHORT_SHA: ${GITHUB_SHA::7}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
    - name: Terraform init
      id: init
      run: |
        tree
        terraform init
      working-directory: development
      shell: bash
    - name: Terraform plan
      id: plan
      run: |
        terraform plan -out tf-$ENVIRONMENT-${GITHUB_SHA::7}.plan -input=false -lock=false
        tree
      working-directory: development
      shell: bash
    - name: Setup Environment (Push)  
      shell: bash  
      run: |  
        echo "LAST_COMMIT_SHA=${GITHUB_SHA::7}" >> ${GITHUB_ENV}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plan-${{ env.LAST_COMMIT_SHA }}
        path: development/tf-${{ env.ENVIRONMENT }}-${{ env.LAST_COMMIT_SHA }}.plan
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    #   run: terraform apply -input=false tf.plan
    #   env:
    #     ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #     ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    #     ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    #     ENVIRONMENT: development
    #   working-directory: development
    #   shell: bash