name: Deploy Terraform infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-tf-modules:
    runs-on: ubuntu-latest
    name: Terraform init
    environment: development
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ENVIRONMENT: development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        terraform_wrapper: false
    - name: Terraform init
      id: init
      run: |
        tree
        terraform init
      working-directory: development
      shell: bash
    - name: Terraform plan
      id: plan
      run: terraform plan -out tf.plan -input=false -lock=false
      working-directory: development
      shell: bash

  deploy-infra:
    uses: lRaggnar/poc-gh-actions-terraform/.github/workflows/deploy-terraform.yml@main
    with:
      working-directory: development
    secrets:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ENVIRONMENT: development